### ISSUE TITLE
Code Review Suggestions

### ISSUE THREAD

**Issue by jordanjones98** [ricabruinsma/grocerySales#1]
- See if there is a coupon API instead of scraping. (Might be a little easier than trying to scrape)
- May want to look into creating a stores table to be able to assign coupons to a store
- Add timestamps to tables
- git ignore .idea metadata

**Comment by pawaitemadisoncollege** [comment]
@jordanjones98 Remember when providing feedback to include those "kudos" items too!

**Comment by ricabruinsma** [comment]
Thank you for the suggestions!!

I must not have explained clearly... I'm not going to attempt coupons in V1.  I'm planning to screen scrape to get the latest sale prices from a store.
I did create a store table - yes, I missed this on first pass!
I added timestamps to all tables.
Could you (oh git master) suggest how I can get rid of the .idea files I've already pushed to git?
