### ISSUE TITLE
Code Review #1 from Xinan Wan

### ISSUE THREAD

**Issue by xinanwan** [ricabruinsma/grocerySales#2]
Item | Considerations | Comments/Suggestions
-- | -- | --
  |   | Reviewer comments and suggestions go here. Each item should have at least one "kudos" and two suggestions for improvement
Problem Statement | 1. Accurately describes project purpose2. Is professional and free of typos, slang, etc.3. Fully explains the problem and the solution4. Is understandable by the average person | 1. The problem statement is very clear and focused on the problem and intended solution.2. can add details to explain why your website is better than any other store websites with sale offers.3. It would be even better to have a target group of users.
Design Documentation | 1. Navigation/flow through the application is logical and easy to use. 2. The order in which values are displayed are logical and easy to understand/use 3. The order in which the form fields entered are logical and easy to understand/use4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | 1. Screen design is very organized and easy to use, and the application flow is very well-designed. 2.can add how to search deals on map if possible.3.can add the user list to show how the saved list is organized.
Data model/Database | 1. Everything on the screens and problem statement/flow is represented in the model2. There is at least one 1-to-many relationship.3. The model represents good database design | 1.there are severl one to many relationships, and database is well designed covering the application flow.2. some column names are not shown fully, so enlarging the table size might help understanding better.3.adding create date and update date might be helpful to manage.
Code | 1. Proper Maven project structure is used2. a .gitignore file for IntelliJ Java projects has been implemented 3. There is not any redundant or copy/paste code in the JSPs or classes4. Classes are appropriately-sized (no monster classes)Property files are used appropriately: no hard-coded values 5. Logging statements are used rather than System.out.println and printStackTrace.6. There are appropriate unit tests/code coverages. | 1.Codes are well written and clean with well-covered unit tests. 2. using project lombak and generic dao can shorten the codes. 3.keep working on jsps so you can display some results!

**Comment by ricabruinsma** [comment]
Thank you for the suggestions! I am getting caught up with Lombok and the GenericDao, and working on basic jsps. 
I made the updates to the databases, including create/update dates.
I updated the problem statement to include why my web app is a valuable contribution.
