### ISSUE TITLE
Code review feedback

### ISSUE THREAD

**Issue by jacquesmatcgithub** [ricabruinsma/grocerySales#3]
# Design/Code Review 3

#### Reviewer: Jacques Fourie

|Category|Criteria|Rating/Comments|
|--------|---------|---------------|
|**Project Overview**|| |
| | Which planned functionality has been met? |User login, Authentication, Read functionality on user. Database design.|
| | Which planned functionality has not been met? | User signup & update. Adding & deleting item to/from shopping list. Consume grocery deals API. Implement UI/web template.  ||
||Describe the GitHub history and what it demonstrates about the project progress during the semester.| There is a good frequency of work but I suspect Rica does not push to Github as often as she may would like to. |
||Describe how peer and instructor feedback/recommendations were incorporated into the project.| Went with most suggestions when possible. |
||Other comments/notes?|  |
|**JSPs**|| |
||Evaluate the JSPs for templating, business logic, data validation, overall look and feel.| There's an oportunity here to make more use of templates. I found once I templated my jsp pages making changes became much easier and conformative.|
||Other comments/notes?|  |
|**Java code quality**|Evaluate the code quality for the following and identify specific areas for improvement (class, method or line number) <li>single-purpose methods <li>well-structured project <li>descriptive naming of packages, classes, methods, variables <li>classes appropriately-sized  (no monster classes) <li> CPD (copy paste detection, meaning are the same lines of code repeated?) <li>are there candidates for super/subclass relationships, abstract classes, interfaces? <li>are any values hard-coded that should be in a properties file? <li>proper exception handling <li>proper error reporting to the user <li> code documentation | I love that Rica is using Lombok in every one of her entity classes. I really wanted to explore that myself, but just never had the time or courage (things tend to break badly when I fiddle with too much :-)  |Other comments/notes?| |
|**Logging**|Evaluate the use of logging, for example:<li>appropriate use of logging statements in the code for error logging and debugging <li>logging levels used - info, debug, error <li> no occurrences of  System.out.printlns or printStackTrace() <li> logging works on AWS deploy| Unfortiunately I did not see much in the way of logging. There are some, but not as much as expected.|Other comments/notes?| |
|**Unit Tests**|Evaluate the unit tests, for example: <li>tests are truly a unit test rather than a high level functional test <li>test data is appropriately cleaned up or handled <li> there is full coverage of methods that perform business logic or utility functions <li>redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After | Rica has unit tests for every one of her Daos. They look really good and Rica demonstrated they all come back 'green'  :-)
| |Other comments/notes?| |
|**Security**|Evaluate authentication/authorization:| Tomcat authentication is in place. |
||Is it implemented correctly and working locally as well as on AWS? | Yes
||Other comments/notes?| |
|**Web Service/API integration**|Evaluate the service/api integration, for example: <li> Which service/api is implemented? <li>How is  error handling of the service implemented? For example, what happens if the service is not available?| Rica is planning on integrating her team project API into her project. I think that is great that she has an oportunity to do that.  |
||Other comments/notes?| |
|**Independent research topic**| What is the independent research topic?| JSoup screen scraping. When Rica was doing her team project they successfully researched how to achieve screen scraping using Jsoup and she intends on incorporating the API they built using Jsoup into her project. |
||Is the independent research topic/technique implemented in the project?| Not yet. |
||Other comments/notes?| |
|**Deployment**| Has the application been successfully deployed to AWS?| Yes, in a previous incarnation. The latest version will be deployed in the near future. |
||Is the hosted application fully functioning?| Not yet |
||Other comments/notes?| I love the creative aspect of Rica's project. This is the sort of app I would actually use in real life. |

**Comment by ricabruinsma** [comment]
Thank you for your review and suggestions.
