### ISSUE TITLE
Instructor Feedback - Week 14

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [ricabruinsma/grocerySales#4]
Since you are on the schedule to present next week, I thought a little review might be helpful.

- [x] For consistency, consider adding the same styling to your error page and log-in page as the rest of your site.
- [x] What is the user experience if the db is down or the service you depend on is not working? A custom error page to hide things like the stack trace accompanying most 500 errors would be ideal, as those stack traces can reveal things about your site and db that you likely don't want known.
- [x] Review the secured resources in web.xml, and consider which jsps and servlets should be restricted. A savvy user might try to guess servlet urls, so it's important to restrict access to those as well.
- [ ] Remember to isolate hard-coded values into properties files. https://github.com/ricabruinsma/grocerySales/blob/3778bdce68a7f1ed91886085c45c246743e5c943/src/main/java/edu/matc/controller/Scraper.java#L14
- [x]  Remember javadoc https://github.com/ricabruinsma/grocerySales/blob/3778bdce68a7f1ed91886085c45c246743e5c943/src/main/java/edu/matc/entity/User.java#L78-L80. Easy to generate with the plugin which means maybe that is one of the very last task list items, if it isn't already.

**Comment by ricabruinsma** [comment]
I think I hit most of these, minus the hard-coded values.  In the job hustling version.
